version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: django-drf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Map host port 5433 to container port 5432
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db  # Ensure the database service is up before starting Django
    env_file:
      - ./prod.env  # Explicitly loading prod.env
    environment:
      - ENV=prod
      - DATABASE_URL=postgres://postgres:PASSWORD@db:5432/django-drf  # Keep internal port
    volumes:
      - .:/usr/src/app  # Mount the current directory to the app directory
    command: [ "./entrypoint.sh" ]

volumes:
  postgres_data:
