# Generated by Django 3.2.25 on 2024-10-25 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('educator', 'Educator'), ('company', 'Company'), ('candidate', 'Candidate')], max_length=128)),
                ('trade_name', models.CharField(max_length=256, null=True)),
                ('corporate_name', models.CharField(max_length=256, null=True)),
                ('numbers_employees', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=128, null=True)),
                ('cnpj', models.CharField(max_length=128, null=True)),
                ('cpf', models.CharField(max_length=128, null=True)),
                ('profession', models.CharField(max_length=128, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('google_email_verification', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_agreement_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='complete', max_length=128)),
                ('email_token_used', models.BooleanField(default=False)),
                ('forgot_password_token_used', models.BooleanField(default=True)),
                ('is_de_activated', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='userentity_groups', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='userentity_permissions', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
